[package]
name = "mineshaft_api"
version = "0.1.0"
authors = ["Samuel Barney <samjbarney@gmail.com>"]
edition = "2018"

[dependencies]
json = "*"
nalgebra = "0.18"
nbtrs = {git="https://github.com/overviewer/nbtrs"}
rand = "0.6.5"
