[package]
name = "chorus_api"
version = "0.1.0"
authors = ["Samuel Barney <samjbarney@gmail.com>"]
edition = "2018"

[dependencies]
json = { git = "https://github.com/mineshaft-server/json-rust.git" }
log = "0.4"
nalgebra = "0.18"
rand = "0.6.5"
